sname: Android Test Report
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run Lint
        run: ./gradlew LintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v@v3.0.0
        with:
          name: lint.html
          path: /Users/ozdemiroz/AndroidStudioProjects/MyNews2/app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v@v3.0.0
        with:
          name: unit_test_report
          path:  /Users/ozdemiroz/AndroidStudioProjects/MyNews2/app/build/outputs

  instrumentation-test:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v@v3.0.0

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Upload test report
        uses: actions/upload-artifact@v@v3.0.0
        with:
          name: instrumentation_test_report
          path:  /Users/ozdemiroz/AndroidStudioProjects/MyNews2
